"use strict";

var CONFIG_OPTIONS = {
  CONFIG_LANGUAGES: [
    ["en-us",   "English (United States)"],
    ["he-il",   "עברית (ישראל)"],
    ["ja-jp",   "Japanese (Japan)"],
    ["ko-kr",   "Korean (South Korea)"],
    ["ru-ru",   "Russian (Russia)"],
    ["zh-cn",   "Simplified Chinese (China)"],
    ["zh-tw",   "Traditional Chinese (Taiwan)"],
  ],
  CONFIG_VERSIONS: [
    ["master",  "Development"],
    ["latest",  "Latest Release"],
    ["4.0",     "Release 4.0"],
    ["newline", "newline"],
    ["3.31",    "Release 3.31"],
    ["3.30",    "Release 3.30"],
    ["3.29",    "Release 3.29"],
    ["3.26",    "Release 3.26"],
    ["3.25",    "Release 3.25"],
    ["3.24",    "Release 3.24"],
    ["3.23",    "Release 3.23"],
    ["3.22",    "Release 3.22"],
    ["3.20",    "Release 3.20"],
    ["3.19",    "Release 3.19"],
    ["3.18",    "Release 3.18"],
    ["3.17",    "Release 3.17"],
    ["3.16",    "Release 3.16"],
    ["3.15",    "Release 3.15"],
    ["3.14",    "Release 3.14"],
    ["3.13",    "Release 3.13"],
    ["3.12",    "Release 3.12"],
    ["3.11",    "Release 3.11"],
    ["3.10",    "Release 3.10"],
    ["3.9",     "Release 3.9"],
    ["3.8",     "Release 3.8"],
    ["3.7",     "Release 3.7"],
    ["3.6",     "Release 3.6"],
    ["3.5",     "Release 3.5"],
    ["3.4",     "Release 3.4"],
    ["3.3",     "Release 3.3"],
    ["3.2",     "Release 3.2"],
    ["3.1",     "Release 3.1"],
    ["3.0",     "Release 3.0"],
  ],
  CONFIG_PROJECTS: [
    ["Crowdin", "https://ltdorgtest.crowdin.com/cmake-docs-l10n"],
    ["GitHub",  "https://github.com/ltdorgtest/cmake-docs-l10n"],
    ["GitCode", "https://gitcode.com/ltdorgtest/cmake-docs-l10n"],
    ["GitFlic", "https://gitflic.ru/project/ltdorgtest/cmake-docs-l10n"],
  ]
};
