name: Report a Bug
description: Create a report to help us improve
title: "[BUG] "
labels: [bug]
assignees:
  - hwhsu1231
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: input
    id: title
    attributes:
      label: Bug Title
      description: Write a short, clear title for the bug.
      placeholder: A concise title for the bug
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a more detailed description of the bug.
      placeholder: Describe the bug in detail here.
    validations:
      required: true
