name: Request a New Language
description: Use this template for requesting a new language.
title: "[LANG] Request a New Language '<language-code>'"
labels:
  - "Language Request"
assignees:
  - hwhsu1231
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this language request!
  - type: textarea
    attributes:
      label: Language Request
      description: |
        Examples:
        - **Language Code:** `zh_CN`
        - **Crowdin Code:** `zh-CN`
        - **ReadTheDocs Code:** `zh_CN`
        - **English Name:** Simplified Chinese
        - **Localized Name:** 简体中文
      value: |
        - **Language Code:**
        - **Crowdin Code:**
        - **ReadTheDocs Code:**
        - **English Name:**
        - **Localized Name:**
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist
      # description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I confirm that the requested language is available in [Language Code Table](https://github.com/ltdorgtest/s2clm).
          required: true
        - label: I confirm that the requested language had a language team created in [Logo Design](https://github.com/ltdorgtest/logo-design).
          required: true
        - label: I confirm that the requested language is not requested in [Issues](https://github.com/ltdorgtest/cmake-docs-l10n/labels/Language%20Request).
          required: true
        - label: I agree to follow this project's [Code of Conduct](https://example.com).
          required: true
