name: Request a New Language
description: Use this template for requesting a new language.
title: "[Langauge] Request New Language '<language-code>'"
labels:
  - "new language"
body:
  - type: textarea
    attributes:
      label: Language Request
      description: |
        Examples:
        - **Locale Code:** `zh_CN`
        - **English Name:** Simplified Chinese
        - **Native Name:** 简体中文
        - **Crowdin Code:** `zh-CN`
        - **ReadTheDocs Code:** `zh_CN`
      value: |
        - **Locale Code:**
        - **English Name:**
        - **Native Name:**
        - **Crowdin Code:**
        - **ReadTheDocs Code:**
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: The language is available in [Language Code Table](https://github.com/ltdorgtest/lang-table).
          required: true
        - label: The language had a language team created in [Logo Design](https://github.com/ltdorgtest/logo-design).
          required: true
        - label: The language is not requested in [Issues](https://github.com/ltdorgtest/cmake-docs-l10n/labels/Language%20Request).
          required: true
        - label: I agree to follow this project's [Code of Conduct](https://example.com).
          required: true
